### ISSUE TITLE
Results over Unwraps

### ISSUE THREAD

**Issue by appcypher** [Lord-sarcastic/lazerpay-rust-sdk#12]
Might want to return Results instead of unwrapping. This puts error handling into the users hands and prevents unexpected and sometimes unwanted panics.

**Comment by Lord-sarcastic** [comment]
Yeah, does make sense. What's your take on custom error types instead? Rather than just the status code. Users would rely on the SDK to simplify Lazerpay's API responses rather than they having to write code to interpret errors. So, I think custom error types is quite good so the user can handle what is there underneath.
What do you think?

**Comment by appcypher** [comment]
If Lazerpay has a stable error API, it might make sense to have something that is more user friendly while also providing a way for users to get the errors as the devs intended them.
